#cloud-config
ssh_authorized_keys:
  - "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDO6C9oQUMu4IpsOMbstuJgjVOu35DGedtAZ0IH1aluKCKWCiXHLdtCxbYfXyrbAh4BbkyIqPX3QitFyti251gkAYYEcp3bvVk/u0Dg8q1uxRxnNvH2+yTP2LWci20UfZ9SUo54BoGVnRnmvVYmS9D1tHJ7oTAXAbrPeNeHZVfr34fYKwibTTpEQ+rtxPxuj/xgjv7BDMMkMLRyMnPwzf9wB3+HT5dFb5v2zaaj1XjC6Qibsp4lZifnS7MjeEI+nxK6aw8dxazA3p0gdM/RZgH71bGgQ+AQchdIFnhhm2HGK5nWYvbRuWXWzjn6hgIvLRnH1RVD3NZX48aiSHqCNH3t dsi@zenoss.economat.local"
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDCX8uF7dsmLGqmXSHbVMgywo0vhR5muKFTL277i//Ze9ed1rkQW6nYGm3Tjk4/2NWaqSqyRNFbi9c1X3vgArwL/dSKIbu+HhuW6BO9l3IM3sR3BxmoU8wZD2TySO82QD9bWpn0Y2zNkRxVGddvuF5VQVeVeA7J5oBRaEEI0HNNBY/66Go9tIOj77KKyzFk53uxeWVOYkNP5a7RQvJJOui5Po0EkbJG0rhAXKQ305c+0DBcU1rs5VOD4W9AjCZ/LVM3cU78JzIU25Vu1b1EVSQxSAu3TNB0XhsDTKFwRDXzU1RaIgUGZ/ycD8qZj8tUlRqJwl4Xyx1uo1pckqf/ReC3 fjudith@economat.local
users:
  - name: "k8s-vsphere"
    passwd: "$6$rounds=4096$CTygOwZxVTX4af$5ejvcx4QqA3Aoul/5zboIzj18rf/zg8UXhGoW9lCtnhooRDbrlWQzr8P.vTcezOwSk.FEAOcJzoxEGzYgTAg10"
    groups:
      - "sudo"
      - "docker"
coreos:
  update:
    reboot-strategy: "off"
  units:
    - name: docker.service
      enable: true
    - name: coreos-cloudinit-vsphere-mkdir.service
      command: start
      runtime: yes
      content: |
        [Service]
        Type=oneshot
        ExecStart=/bin/mkdir -p /var/lib/coreos-vsphere
    - name: coreos-cloudinit-vsphere-user.path
      command: start
      runtime: yes
      content: |
        [Path]
        PathExists=/var/lib/coreos-vsphere/vsphere-user-data
        Unit=user-cloudinit@var-lib-coreos\x2dvsphere-vsphere\x2duser\x2ddata.service
write_files:
  - path: /etc/environment
    owner: root
    permissions: '0644'
    content: |
      COREOS_PUBLIC_IPV4=$private_ipv4
      COREOS_PRIVATE_IPV4=$private_ipv4
  - path: /run/coreos-kubernetes/options.env
    owner: root
    permissions: '0644'
    content: |
      ETCD_ENDPOINTS={{ETCD_ENDPOINTS}}