#cloud-config
# https://coreos.com/etcd/docs/latest/etcd-live-cluster-reconfiguration.html
# https://coreos.com/os/docs/latest/provisioning.html
# https://coreos.com/etcd/docs/latest/v2/configuration.html

coreos:
  update:
    reboot-strategy: "off"
  units:
    - name: etcd-member.service
      enable: true
      command: start
      content: |
        [Unit]
        Description=etcd (System Application Container)
        Documentation=https://github.com/coreos/etcd
        Wants=network-online.target network.target
        After=network-online.target
        Conflicts=etcd.service
        Conflicts=etcd2.service

        [Service]
        Type=notify
        Restart=on-failure
        RestartSec=10s
        TimeoutStartSec=0
        LimitNOFILE=40000
        Environment="ETCD_IMAGE_TAG=v3.2.11"
        Environment="ETCD_NAME={{ETCD_NODE_NAME}}"
        Environment="ETCD_USER=etcd"
        Environment="ETCD_DATA_DIR=/var/lib/etcd"
        Environment="RKT_RUN_ARGS=--uuid-file-save=/var/lib/coreos/etcd-member-wrapper.uuid"

        Environment="ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379"
        Environment="ETCD_ADVERTISE_CLIENT_URLS=http://$private_ipv4:2379"
        Environment="ETCD_LISTEN_PEER_URLS=http://$private_ipv4:2380"
        Environment="ETCD_INITIAL_ADVERTISE_PEER_URLS=http://$private_ipv4:2380"
        Environment="ETCD_INITIAL_CLUSTER={{ETCD_INITIAL_CLUSTER}}"
        Environment="ETCD_STRICT_RECONFIG_CHECK=true"

        ExecStartPre=/usr/bin/mkdir --parents /var/lib/coreos
        ExecStartPre=-/usr/bin/rkt rm --uuid-file=/var/lib/coreos/etcd-member-wrapper.uuid
        ExecStart=/usr/lib/coreos/etcd-wrapper $ETCD_OPTS
        ExecStop=-/usr/bin/rkt stop --uuid-file=/var/lib/coreos/etcd-member-wrapper.uuid

        [Install]
        WantedBy=multi-user.target